# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Barlds blog
tagline:          'A Jekyll theme'
description:      'blog over programmeren en persoonlijke ervaringen
'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Barld Boot'
  url:            https://github.com/barld

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/barld/barld.github.io
